apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-frontend-route
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
  hostnames:
    - {{ .Values.domain.frontend | quote }}
  rules:
    - backendRefs:
        - name: {{ .Release.Name }}-frontend
          port: {{ .Values.frontend.service.port }}